//! The decision documents archwarden writes and a human edits.
//!
//! # One owner, and a region that is not the tool's
//!
//! A decision's reasoning is three paragraphs. JSON has no comments (decision
//! 5), `why` is one string, and `link` points somewhere archwarden cannot
//! read — so a team either wrote a sentence where a page was needed, or kept
//! the real ADR where nothing joined it to the rules.
//!
//! This is not two owners. It is **one owner and a rendering with a
//! hand-written region**: everything the config knows is generated from the
//! config, and one marked region belongs to whoever opens the file. That is
//! the shape `schema/v0.json` and `cargo xtask check-schema` already use, and
//! this repository has decided it believes in it. Issue #116.
//!
//! # What is *not* here
//!
//! No numbering, no template, no opinion about what an ADR should contain.
//! archwarden writes down what it can check and leaves the rest of the page
//! blank for a person.

use std::fmt::Write as _;

use archwarden_core::compiled::{CompiledConfig, CompiledDecision};
use camino::{Utf8Path, Utf8PathBuf};

/// Where the documents live, relative to the repository root.
///
/// Beside `baseline.json` and not inside `cache/`: the first is a file the
/// tool writes and the repository commits, the second is gitignored. These are
/// the first kind. Writing here can never collide with a file somebody
/// maintains by hand, which is the risk in a `docs/adr/` a team already owns.
pub const DECISIONS_DIR: &str = ".archwarden/decisions";

/// Where the human's region opens.
pub const YOURS_OPEN: &str = "<!-- archwarden:yours -->";
/// Where it closes. Everything between the two survives a regeneration.
pub const YOURS_CLOSE: &str = "<!-- archwarden:end -->";

/// One document, as it would be written.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Document {
    /// Where it goes, relative to the repository root.
    pub path: Utf8PathBuf,
    /// The whole file.
    pub body: String,
}

/// What writing the documents would do.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Changes {
    /// Documents that do not exist yet.
    pub created: Vec<Utf8PathBuf>,
    /// Documents whose generated half no longer matches the config.
    pub updated: Vec<Utf8PathBuf>,
    /// Documents already byte-identical to what would be written.
    pub unchanged: Vec<Utf8PathBuf>,
}

impl Changes {
    /// Whether writing would leave every file exactly as it is.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.created.is_empty() && self.updated.is_empty()
    }
}

/// The text a person wrote in this file, if the file has any.
///
/// Extracted rather than diffed: one delimited region, taken out whole and
/// spliced back into a freshly generated file. A generator that tried to
/// preserve several regions would be a merge algorithm, and a merge algorithm
/// that is wrong once eats somebody's paragraph.
#[must_use]
pub fn yours(existing: &str) -> Option<&str> {
    let start = existing.find(YOURS_OPEN)? + YOURS_OPEN.len();
    let end = existing[start..].find(YOURS_CLOSE)? + start;
    Some(existing[start..end].trim_matches('\n'))
}

/// The document for one decision, with `kept` spliced into the human region.
#[must_use]
pub fn render(config: &CompiledConfig, decision: &CompiledDecision, kept: Option<&str>) -> String {
    let serving: Vec<&str> = config
        .rules()
        .filter(|rule| rule.decision.as_ref() == Some(&decision.id))
        .map(|rule| rule.id.as_str())
        .collect();

    let mut out = String::new();
    // Frontmatter, and it says out loud that it is generated. A reader who
    // edits it and loses the edit was told not to, in the file.
    let _ = writeln!(out, "---");
    let _ = writeln!(out, "# generated by `archwarden decisions`. do not edit.");
    let _ = writeln!(out, "id: {}", decision.id);
    let _ = writeln!(out, "status: {}", decision.status);
    if !decision.supersedes.is_empty() {
        let _ = writeln!(out, "supersedes: [{}]", join(&decision.supersedes));
    }
    if !decision.superseded_by.is_empty() {
        let _ = writeln!(out, "superseded_by: [{}]", join(&decision.superseded_by));
    }
    if !serving.is_empty() {
        let _ = writeln!(out, "enforced_by: [{}]", serving.join(", "));
    }
    if let Some(scope) = &decision.scope {
        let _ = writeln!(out, "scope: [{}]", scope.patterns().join(", "));
    }
    if let Some(link) = &decision.link {
        let _ = writeln!(out, "link: {link}");
    }
    let _ = writeln!(out, "---\n");

    let _ = writeln!(out, "# {}\n", decision.title);
    if let Some(why) = &decision.why {
        let _ = writeln!(out, "> {why}\n");
    }
    // Above the human's region and in prose, not only in the frontmatter: the
    // reader this line is for is one standing in those paths, and they are
    // reading the document rather than parsing it.
    if let Some(scope) = &decision.scope {
        let paths: Vec<String> = scope
            .patterns()
            .iter()
            .map(|pattern| format!("`{pattern}`"))
            .collect();
        let _ = writeln!(out, "Applies to {}.\n", paths.join(", "));
    }

    // The human's region sits here, between what the config says and the
    // appendices it generates: a reader arrives at the claim, then the
    // context, then the evidence.
    let _ = writeln!(out, "{YOURS_OPEN}");
    match kept.filter(|kept| !kept.trim().is_empty()) {
        Some(kept) => {
            let _ = writeln!(out, "\n{kept}\n");
        }
        // A prompt rather than a blank. An empty region is one nobody fills.
        None => {
            let _ = writeln!(
                out,
                "\n## Context\n\n_Everything between these two markers is \
                 yours. archwarden never rewrites it._\n"
            );
        }
    }
    let _ = writeln!(out, "{YOURS_CLOSE}\n");

    if !decision.alternatives.is_empty() {
        let _ = writeln!(out, "## Considered and rejected\n");
        for alternative in &decision.alternatives {
            let refused = match &alternative.refused_by {
                Some(rule) => format!("refused by `{rule}`"),
                None => "nothing refuses it".to_owned(),
            };
            let _ = writeln!(
                out,
                "- **{}** ({refused}) — {}",
                alternative.option, alternative.why_not
            );
        }
        let _ = writeln!(out);
    }

    let _ = writeln!(out, "## What keeps it\n");
    if serving.is_empty() {
        // The claim answers exactly the question this section asks, so it is
        // the answer rather than a fourth section of its own. "Nothing" alone
        // reads as an omission, and a decision carrying a reason has said it
        // is not one.
        match &decision.why_not_enforceable {
            Some(why) => {
                let _ = writeln!(out, "Nothing can. {}\n", sentence(why));
            }
            None => {
                let _ = writeln!(
                    out,
                    "Nothing. This decision is written down and not enforced.\n"
                );
            }
        }
    } else {
        for rule in &serving {
            let _ = writeln!(out, "- `{rule}`");
        }
        let _ = writeln!(out);
    }

    out
}

/// A config field read as a sentence: first letter up, full stop at the end.
///
/// `why_not_enforceable` is written to be printed inline after a colon --
/// "nothing can check this: the broker is chosen in infrastructure" -- and the
/// same words have to stand alone here. Rewriting them by hand in the config
/// would mean the field reads wrong in one surface or the other.
fn sentence(why: &str) -> String {
    let trimmed = why.trim();
    let mut chars = trimmed.chars();
    let mut out: String = match chars.next() {
        Some(first) => first.to_uppercase().chain(chars).collect(),
        None => return String::new(),
    };
    if !out.ends_with(['.', '!', '?']) {
        out.push('.');
    }
    out
}

fn join(ids: &[archwarden_core::ids::DecisionId]) -> String {
    ids.iter()
        .map(std::string::ToString::to_string)
        .collect::<Vec<_>>()
        .join(", ")
}

/// Every document this configuration would produce, in declaration order.
#[must_use]
pub fn documents(root: &Utf8Path, config: &CompiledConfig) -> Vec<Document> {
    config
        .decisions()
        .map(|decision| {
            let path = Utf8PathBuf::from(DECISIONS_DIR).join(format!("{}.md", decision.id));
            let existing = std::fs::read_to_string(root.join(&path)).unwrap_or_default();
            Document {
                body: render(config, decision, yours(&existing)),
                path,
            }
        })
        .collect()
}

/// What writing them would change, without writing anything.
#[must_use]
pub fn changes(root: &Utf8Path, config: &CompiledConfig) -> Changes {
    let mut changes = Changes::default();
    for document in documents(root, config) {
        match std::fs::read_to_string(root.join(&document.path)) {
            Ok(existing) if existing == document.body => changes.unchanged.push(document.path),
            Ok(_) => changes.updated.push(document.path),
            Err(_) => changes.created.push(document.path),
        }
    }
    changes
}

#[cfg(test)]
mod tests {
    use super::*;
    use archwarden_core::{
        compiled::{CompiledAlternative, CompiledDecision, DecisionStatus, SkipDirs},
        glob::PathSet,
        hash::ContentHash,
        ids::{DecisionId, RuleId},
        scope::Scope,
    };

    fn decision(alternatives: Vec<CompiledAlternative>) -> CompiledDecision {
        CompiledDecision {
            scope: None,
            why_not_enforceable: None,
            id: DecisionId::new("ADR-031").expect("valid"),
            title: "The domain does not know about transport".to_owned(),
            why: Some(
                "it is published, and a consumer must not inherit our HTTP client".to_owned(),
            ),
            link: None,
            status: DecisionStatus::Accepted,
            supersedes: vec![DecisionId::new("ADR-009").expect("valid")],
            superseded_by: Vec::new(),
            alternatives,
        }
    }

    fn config_of(decisions: Vec<CompiledDecision>) -> CompiledConfig {
        CompiledConfig::new(
            Vec::new(),
            PathSet::default(),
            SkipDirs::default(),
            ContentHash::of(b""),
        )
        .with_decisions(decisions)
    }

    /// Issue #165. A field added to the config and not to the renderer is
    /// drift by construction -- decision 116 made the config the owner and the
    /// document a rendering of it, so every repository that has run
    /// `decisions --write` would get a stale-document concern on upgrade, and
    /// the concern would be right.
    #[test]
    fn the_claim_and_the_scope_reach_the_document() {
        let mut scoped = decision(Vec::new());
        scoped.why_not_enforceable =
            Some("the broker is chosen in infrastructure, not in code".to_owned());
        scoped.scope =
            Some(Scope::compile(["packages/queue/**", "services/worker/**"]).expect("valid scope"));

        let config = config_of(vec![scoped]);
        let page = render(&config, config.decisions().next().expect("one"), None);

        // Machine-readable, next to the other fields the config owns.
        assert!(
            page.contains("scope: [packages/queue/**, services/worker/**]"),
            "{page}"
        );
        // And in prose, because a reader standing in those paths is who the
        // scope is for.
        assert!(
            page.contains("Applies to `packages/queue/**`, `services/worker/**`."),
            "{page}"
        );
        // The claim answers the question "what keeps it" asks, so it is the
        // answer rather than a fourth section: "nothing" alone reads as an
        // omission, and this decision has declared it is not one.
        assert!(
            page.contains("Nothing can. The broker is chosen in infrastructure, not in code."),
            "{page}"
        );
        assert!(
            !page.contains("written down and not enforced"),
            "the bare sentence is for a decision that has not said why: {page}"
        );
        // Generated, so above the human's region -- never inside it.
        let claim = page.find("Nothing can.").expect("the claim");
        let close = page.find(YOURS_CLOSE).expect("the marker");
        assert!(claim > close, "{page}");
    }

    /// A decision with neither renders as it always has. The bare sentence is
    /// the one #160 exists to stop being the only option, not one to remove.
    #[test]
    fn a_decision_with_neither_renders_as_before() {
        let config = config_of(vec![decision(Vec::new())]);
        let page = render(&config, config.decisions().next().expect("one"), None);

        assert!(!page.contains("scope:"), "{page}");
        assert!(!page.contains("Applies to"), "{page}");
        assert!(
            page.contains("Nothing. This decision is written down and not enforced."),
            "{page}"
        );
    }

    /// The generated half is everything the config knows, and it says out loud
    /// that it is generated — a reader who edits the frontmatter and loses the
    /// edit was told not to, in the file.
    #[test]
    fn the_generated_half_is_everything_the_config_knows() {
        let config = config_of(vec![decision(vec![CompiledAlternative {
            option: "an HTTP client in the domain".to_owned(),
            why_not: "a consumer would inherit our transport".to_owned(),
            refused_by: Some(RuleId::new("domain-forbids-http").expect("valid")),
        }])]);
        let page = render(&config, config.decisions().next().expect("one"), None);

        assert!(page.starts_with("---\n# generated by"), "{page}");
        assert!(page.contains("id: ADR-031"), "{page}");
        assert!(page.contains("supersedes: [ADR-009]"), "{page}");
        assert!(
            page.contains("# The domain does not know about transport"),
            "{page}"
        );
        assert!(
            page.contains("> it is published, and a consumer must not inherit"),
            "the `why` is rendered here rather than moved out of the config: {page}"
        );
        assert!(
            page.contains(
                "- **an HTTP client in the domain** (refused by `domain-forbids-http`) \
                 — a consumer would inherit our transport"
            ),
            "{page}"
        );
        assert!(
            page.contains("Nothing. This decision is written down and not enforced."),
            "{page}"
        );
    }

    /// The whole promise of the file: regenerating never eats what a person
    /// wrote. Everything else may be rewritten; this may not.
    #[test]
    fn regenerating_keeps_what_a_person_wrote() {
        let config = config_of(vec![decision(Vec::new())]);
        let first = render(&config, config.decisions().next().expect("one"), None);

        let edited = first.replace(
            "## Context\n\n_Everything between these two markers is yours. \
             archwarden never rewrites it._",
            "## Context\n\nThree services shared the order model and each one \
             stored it its own way.",
        );
        assert_ne!(edited, first, "the fixture edited the region it meant to");

        let again = render(
            &config,
            config.decisions().next().expect("one"),
            yours(&edited),
        );

        assert!(
            again.contains("Three services shared the order model"),
            "{again}"
        );
        assert!(
            !again.contains("archwarden never rewrites it"),
            "the prompt is replaced by what was written over it: {again}"
        );
    }

    /// And a file with no markers at all — hand-written, or from a version
    /// before this — contributes nothing rather than being spliced wrongly.
    #[test]
    fn a_file_with_no_region_gives_nothing_back() {
        assert_eq!(yours("# just a heading\n\nsome prose"), None);
        assert_eq!(
            yours(&format!("{YOURS_OPEN}\nkept\n{YOURS_CLOSE}")),
            Some("kept")
        );
        assert_eq!(
            yours(&format!("{YOURS_OPEN}\nunclosed")),
            None,
            "an unclosed region is not a region: splicing it would swallow the rest of the file"
        );
    }

    /// The frontmatter is a machine-readable index of the same facts, so a
    /// script can find every document a rule serves without parsing the prose.
    /// Every list in it names only what belongs to *this* decision.
    #[test]
    fn the_frontmatter_indexes_this_decision_and_no_other() {
        let mut serving = archwarden_core::compiled::CompiledRule {
            id: RuleId::new("domain-forbids-http").expect("valid"),
            module: None,
            why: None,
            module_why: None,
            decision: Some(DecisionId::new("ADR-031").expect("valid")),
            imports: None,
            directives: None,
            level: archwarden_core::level::Level::Error,
            scope: archwarden_core::scope::Scope::compile(["src/*"]).expect("valid"),
            kind: archwarden_core::compiled::CompiledRuleKind::Frozen,
        };
        let elsewhere = archwarden_core::compiled::CompiledRule {
            id: RuleId::new("someone-elses-rule").expect("valid"),
            decision: Some(DecisionId::new("ADR-009").expect("valid")),
            ..serving.clone()
        };
        serving.decision = Some(DecisionId::new("ADR-031").expect("valid"));

        let mut replaced = decision(Vec::new());
        replaced.superseded_by = vec![DecisionId::new("ADR-099").expect("valid")];

        let config = CompiledConfig::new(
            vec![serving, elsewhere],
            PathSet::default(),
            SkipDirs::default(),
            ContentHash::of(b""),
        )
        .with_decisions(vec![replaced]);
        let page = render(&config, config.decisions().next().expect("one"), None);

        assert!(
            page.contains("enforced_by: [domain-forbids-http]"),
            "{page}"
        );
        assert!(
            !page.contains("someone-elses-rule"),
            "a rule serving another decision is not this decision's evidence: {page}"
        );
        assert!(page.contains("superseded_by: [ADR-099]"), "{page}");
        assert!(
            page.contains("- `domain-forbids-http`"),
            "and it is named again where a reader looks for it: {page}"
        );
    }

    /// A decision that says less produces a shorter file rather than a file
    /// with empty headings in it.
    #[test]
    fn a_decision_that_says_less_writes_less() {
        let bare = CompiledDecision {
            scope: None,
            why_not_enforceable: None,
            id: DecisionId::new("ADR-1").expect("valid"),
            title: "A wall".to_owned(),
            why: None,
            link: None,
            status: DecisionStatus::Accepted,
            supersedes: Vec::new(),
            superseded_by: Vec::new(),
            alternatives: Vec::new(),
        };
        let config = config_of(vec![bare]);
        let page = render(&config, config.decisions().next().expect("one"), None);

        assert!(!page.contains("supersedes:"), "{page}");
        assert!(!page.contains("superseded_by:"), "{page}");
        assert!(
            !page.contains("enforced_by:"),
            "an empty list is left out rather than written as `[]`: {page}"
        );
        assert!(!page.contains("Considered and rejected"), "{page}");
        assert!(
            !page.contains("\n> "),
            "a decision with no `why` grows no empty blockquote: {page}"
        );
    }
}
