//! `cargo xtask clean` — the build caches, and how much of them to keep.
//!
//! `cargo clean` is all or nothing, and all is usually wrong: it throws away
//! the compiled dependencies too, so the next build is a cold one for the sake
//! of space that was not the problem. The space that *is* the problem is
//! incremental compilation state, which grows without bound and buys a few
//! seconds per rebuild.
//!
//! Measured on this repository, once: `target` was 59 GB, of which
//! `debug/incremental` was 27 and `debug/deps` was 28. The default tier here
//! takes the 27 and leaves the 28, so a rebuild after it is still warm.
//!
//! # What it will not take
//!
//! `target/criterion` holds benchmark history, and a benchmark that cannot be
//! compared against its own past is a number with nothing to say. It is small,
//! it is *data* rather than cache, and no tier removes it.
//!
//! # Orphans
//!
//! `cargo-mutants` builds in a copy under the system temporary directory and
//! removes it when it finishes. When it is killed it does not, and each orphan
//! is a whole build tree. They are swept here because nothing else will.

use std::path::{Path, PathBuf};

/// How much to take.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Depth {
    /// Caches that cost a rebuild nothing worth measuring.
    Caches,
    /// Those, and the compiled dependencies. The next build is cold.
    Deps,
    /// Everything under `target`, which is what `cargo clean` does.
    All,
}

impl Depth {
    /// Reads the flag a caller passed.
    pub(crate) fn parse(args: &[String]) -> Result<Self, String> {
        match args
            .iter()
            .map(String::as_str)
            .collect::<Vec<_>>()
            .as_slice()
        {
            [] => Ok(Self::Caches),
            ["--deps"] => Ok(Self::Deps),
            ["--all"] => Ok(Self::All),
            other => Err(format!(
                "unknown argument {other:?}; usage: cargo xtask clean [--deps|--all]"
            )),
        }
    }

    /// What this depth removes, relative to the repository root.
    ///
    /// Named rather than globbed. A glob over a build directory is one typo
    /// away from taking something nobody meant, and this is the one task in
    /// the repository that deletes.
    fn targets(self) -> &'static [&'static str] {
        const CACHES: &[&str] = &[
            // Incremental compilation state. The big one, and the one that
            // buys the least: a few seconds per rebuild for tens of gigabytes.
            "target/debug/incremental",
            "target/release/incremental",
            // A second build tree, made by `cargo llvm-cov`.
            "target/llvm-cov-target",
            // Regenerated by `cargo doc`, read by nobody offline.
            "target/doc",
            // Written by `cargo xtask preview`, which rewrites it anyway.
            "target/preview",
            // `cargo-mutants` scratch output. Both are gitignored, and the
            // `.old` one is a copy the tool keeps of the run before.
            "mutants.out",
            "mutants.out.old",
        ];
        const DEPS: &[&str] = &[
            "target/debug/incremental",
            "target/release/incremental",
            "target/llvm-cov-target",
            "target/doc",
            "target/preview",
            "mutants.out",
            "mutants.out.old",
            "target/debug/deps",
            "target/release/deps",
        ];
        const ALL: &[&str] = &["target", "mutants.out", "mutants.out.old"];

        match self {
            Self::Caches => CACHES,
            Self::Deps => DEPS,
            Self::All => ALL,
        }
    }
}

/// Removes what the depth names, and says how much that was.
///
/// A number, because "freed some space" is the kind of report this repository
/// refuses everywhere else.
pub(crate) fn run(root: &Path, depth: Depth) -> Result<(), String> {
    let mut freed = 0;

    for relative in depth.targets() {
        let path = root.join(relative);
        let size = size_of(&path);
        if size == 0 {
            continue;
        }

        std::fs::remove_dir_all(&path)
            .map_err(|error| format!("cannot remove {}: {error}", path.display()))?;
        println!("  {relative:<34} {:>10}", human(size));
        freed += size;
    }

    for orphan in mutant_orphans() {
        let size = size_of(&orphan);
        // Reported by its own name: an orphan is somebody's killed run, and a
        // reader should be able to tell it from a directory this repository
        // owns.
        if std::fs::remove_dir_all(&orphan).is_ok() {
            println!("  {:<34} {:>10}", orphan.display(), human(size));
            freed += size;
        }
    }

    if freed == 0 {
        println!("nothing to remove.");
    } else {
        println!("\n{} freed.", human(freed));
    }

    if depth == Depth::Caches {
        println!("`deps` was kept, so the next build is still warm. `--deps` takes it too.");
    }

    Ok(())
}

/// Build trees `cargo-mutants` left behind when it was killed.
///
/// Matched by the prefix the tool itself uses. Nothing else is touched in the
/// temporary directory, and a directory that is not ours is not our business
/// even when it is large.
fn mutant_orphans() -> Vec<PathBuf> {
    let Ok(entries) = std::fs::read_dir(std::env::temp_dir()) else {
        return Vec::new();
    };

    entries
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| {
            path.is_dir()
                && path
                    .file_name()
                    .and_then(|name| name.to_str())
                    .is_some_and(|name| name.starts_with("cargo-mutants-"))
        })
        .collect()
}

/// Bytes under a path, or zero when it is not there.
///
/// Walks rather than asking the filesystem, because there is no portable way to
/// ask and this runs once per directory in a task nobody runs in a loop.
fn size_of(path: &Path) -> u64 {
    let Ok(metadata) = std::fs::symlink_metadata(path) else {
        return 0;
    };
    if !metadata.is_dir() {
        return metadata.len();
    }

    let Ok(entries) = std::fs::read_dir(path) else {
        return 0;
    };
    entries
        .filter_map(Result::ok)
        .map(|entry| size_of(&entry.path()))
        .sum()
}

/// `27.4 GB`, for a person.
fn human(bytes: u64) -> String {
    #[expect(
        clippy::cast_precision_loss,
        reason = "a size printed to one decimal place; the loss is below what is shown"
    )]
    let mut size = bytes as f64;
    for unit in ["B", "KB", "MB", "GB"] {
        if size < 1024.0 {
            return format!("{size:.1} {unit}");
        }
        size /= 1024.0;
    }
    format!("{size:.1} TB")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The default tier exists to be safe to run without thinking about it.
    /// Taking `deps` would make the next build cold, which is the cost people
    /// avoid `cargo clean` for in the first place.
    #[test]
    fn the_default_tier_keeps_the_compiled_dependencies() {
        let targets = Depth::Caches.targets();

        assert!(targets.contains(&"target/debug/incremental"));
        assert!(!targets.contains(&"target/debug/deps"));
        assert!(Depth::Deps.targets().contains(&"target/debug/deps"));
    }

    /// Benchmark history is data, not cache. A benchmark that cannot be
    /// compared against its own past is a number with nothing to say.
    #[test]
    fn no_tier_removes_the_benchmark_history() {
        for depth in [Depth::Caches, Depth::Deps] {
            assert!(
                !depth.targets().contains(&"target/criterion"),
                "{depth:?} would take the benchmark history"
            );
        }
    }

    /// `--all` is `cargo clean`, and says so by taking the directory whole.
    #[test]
    fn all_takes_the_whole_target_directory() {
        assert!(Depth::All.targets().contains(&"target"));
    }

    #[test]
    fn the_flags_are_read_and_a_typo_is_refused() {
        assert_eq!(Depth::parse(&[]), Ok(Depth::Caches));
        assert_eq!(Depth::parse(&["--deps".to_owned()]), Ok(Depth::Deps));
        assert_eq!(Depth::parse(&["--all".to_owned()]), Ok(Depth::All));
        assert!(Depth::parse(&["--dpes".to_owned()]).is_err());
    }

    /// It removes what it names and nothing beside it.
    #[test]
    fn only_the_named_directories_go() {
        let dir = tempfile::tempdir().expect("temp dir");
        let root = dir.path();

        for relative in ["target/debug/incremental", "target/debug/deps", "src"] {
            std::fs::create_dir_all(root.join(relative)).expect("create");
            std::fs::write(root.join(relative).join("x"), b"0123456789").expect("write");
        }

        run(root, Depth::Caches).expect("cleans");

        assert!(!root.join("target/debug/incremental").exists());
        assert!(root.join("target/debug/deps").exists(), "deps was kept");
        assert!(root.join("src").exists(), "and nothing outside target");
    }

    /// A directory that is not there is not an error: the task is run on a
    /// tree that has already been cleaned as often as on one that has not.
    #[test]
    fn cleaning_twice_is_not_an_error() {
        let dir = tempfile::tempdir().expect("temp dir");

        run(dir.path(), Depth::Caches).expect("first");
        run(dir.path(), Depth::Caches).expect("second");
    }

    #[test]
    fn sizes_are_readable() {
        assert_eq!(human(512), "512.0 B");
        assert_eq!(human(1024 * 1024), "1.0 MB");
        assert_eq!(human(27 * 1024 * 1024 * 1024), "27.0 GB");
    }
}
