[package]
name = "archwarden-cli"
description = "A fast, declarative architecture linter for TypeScript and JavaScript."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]

[lints]
workspace = true

[[bin]]
name = "archwarden"
path = "src/main.rs"
